spring.application.name=configserver
spring.cloud.config.server.git.uri=https://github.com/chalbimalek/Configserver
spring.cloud.config.server.git.clone-on-start=true
server.port=8888
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true